spring:
  application:
    name: machine-service
  datasource:
    url: jdbc:mysql:///vms_db?cloudSqlInstance=scalar-neovarsity-vms:us-central1:vms-db-instance&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: machine_service_user
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000
server:
  port: ${PORT:8080}